version: '3.8'

services:
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    volumes:
      - ./database:/var/www/html/database
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite
      - ADMINER_DESIGN=pepa-linha 